//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSclApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrivingSclApp.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم تنجح العملية المطلوبة.
        /// </summary>
        public static string ErrorString {
            get {
                return ResourceManager.GetString("ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجمهورية العربية السورية.
        /// </summary>
        public static string Heading1 {
            get {
                return ResourceManager.GetString("Heading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزارة النقل.
        /// </summary>
        public static string Heading2 {
            get {
                return ResourceManager.GetString("Heading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدارس السواقة.
        /// </summary>
        public static string Heading3 {
            get {
                return ResourceManager.GetString("Heading3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مديرية.
        /// </summary>
        public static string Heading4 {
            get {
                return ResourceManager.GetString("Heading4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string Headings {
            get {
                return ResourceManager.GetString("Headings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جامعة دمشق-كلية الهندسة الميكانيكية والكهربائية.
        /// </summary>
        public static string PreparedBy {
            get {
                return ResourceManager.GetString("PreparedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2022.
        /// </summary>
        public static string ProductYear {
            get {
                return ResourceManager.GetString("ProductYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrivingScl.
        /// </summary>
        public static string ProgID {
            get {
                return ResourceManager.GetString("ProgID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظام مدارس السواقة.
        /// </summary>
        public static string ProgName {
            get {
                return ResourceManager.GetString("ProgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
