//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSclData
{
    using System.Data.Entity;

    public partial class DrivingSclEntity : DbContext
    {
        public DrivingSclEntity()
            : base("name=DrivingSclEntity")
        {
            this.Configuration.ProxyCreationEnabled = false;
            this.Configuration.LazyLoadingEnabled = false;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ZGOVERN>()
               .HasMany(e => e.ZCITY)
               .WithRequired(e => e.ZGOVERN)
               .HasForeignKey(e => e.GOV_NB)
               .WillCascadeOnDelete(true);

            modelBuilder.Entity<ZCITY>()
               .HasMany(e => e.ZREGION)
               .WithRequired(e => e.ZCITY)
               .HasForeignKey(e => e.CTY_NB)
               .WillCascadeOnDelete(true);

            modelBuilder.Entity<SCHOOL>()
               .HasMany(e => e.SCHOOLOWNER)
               .WithRequired(e => e.SCHOOL)
               .HasForeignKey(e => e.SCL_NB)
               .WillCascadeOnDelete(true);

            modelBuilder.Entity<ZCITY>()
                .Property(e => e.NAME)
                .IsUnicode(false);
        }

        public DbSet<SCHOOL> SCHOOL { get; set; }
        public DbSet<SCHOOLOWNER> SCHOOLOWNER { get; set; }
        public DbSet<SCLPHONE> SCLPHONE { get; set; }
        public DbSet<ZCATEGORY> ZCATEGORY { get; set; }
        public DbSet<ZCITY> ZCITY { get; set; }
        public DbSet<ZCOMPANY> ZCOMPANY { get; set; }
        public DbSet<ZGOVERN> ZGOVERN { get; set; }
        public DbSet<ZNATION> ZNATION { get; set; }
        public DbSet<ZOWNERTYP> ZOWNERTYP { get; set; }
        public DbSet<ZPERSON> ZPERSON { get; set; }
        public DbSet<ZPRSTYPE> ZPRSTYPE { get; set; }
        public DbSet<ZREGION> ZREGION { get; set; }
        public DbSet<ZSCLSTATUS> ZSCLSTATUS { get; set; }
        public DbSet<ZSCLTYPE> ZSCLTYPE { get; set; }
    }
}
