//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSclData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("DRIVINGSCHOOLS.ZCATEGORY")]
    public partial class ZCATEGORY
    {
        public ZCATEGORY()
        {
            this.ZCATEGORY1 = new HashSet<ZCATEGORY>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public long NB { get; set; }
        public string NAME { get; set; }
        public Nullable<long> PREV_CATG { get; set; }
        public int STUDENT_PER_CAR { get; set; }
        public Nullable<int> STUDENT_PER_MOTO { get; set; }
        public decimal METERS_FOR_STUDENT { get; set; }
        public Nullable<int> MAX_STUDENTS_PER_HALL { get; set; }
        public string NOTE { get; set; }
    
        public virtual ICollection<ZCATEGORY> ZCATEGORY1 { get; set; }
        public virtual ZCATEGORY ZCATEGORY2 { get; set; }
    }
}
