//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSclData
{
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("DRIVINGSCHOOLS.ZGOVERN")]
    public partial class ZGOVERN
    {
        public ZGOVERN()
        {
            this.SCHOOL = new HashSet<SCHOOL>();
            this.ZCITY = new HashSet<ZCITY>();
            this.ZCOMPANY = new HashSet<ZCOMPANY>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [ScaffoldColumn(false)]
        [DisplayName("«·—„“ «·≈·ﬂ —Ê‰Ì")]
        public long NB { get; set; }
        [DisplayName("«·„Õ«›Ÿ…")]
        public string NAME { get; set; }
    
        public virtual ICollection<SCHOOL> SCHOOL { get; set; }
        public virtual ICollection<ZCITY> ZCITY { get; set; }
        public virtual ICollection<ZCOMPANY> ZCOMPANY { get; set; }
    }
}
