//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSclData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("DRIVINGSCHOOLS.ZNATION")]
    public partial class ZNATION
    {
        public ZNATION()
        {
            this.ZPERSON = new HashSet<ZPERSON>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [ScaffoldColumn(false)]
        [DisplayName("«·—„“ «·≈·ﬂ —Ê‰Ì")]
        public long NB { get; set; }
        [DisplayName("«·Ã‰”Ì…")]
        public string NATION { get; set; }
        [DisplayName("«”„ «·œÊ·…")]
        public string CNTRYNAME { get; set; }

        public virtual ICollection<ZPERSON> ZPERSON { get; set; }
    }
}
