//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSclData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("DRIVINGSCHOOLS.ZPERSON")]
    public partial class ZPERSON
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public long NB { get; set; }
        public string NATNO { get; set; }
        public string FNAME { get; set; }
        public string LNAME { get; set; }
        public string FATHER { get; set; }
        public string MOTHER { get; set; }
        public string CIVILLOC { get; set; }
        public string ACTADDRESS { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string MOBILE { get; set; }
        public Nullable<long> BDATED { get; set; }
        public Nullable<long> BDATEM { get; set; }
        public Nullable<long> BDATEY { get; set; }
        public Nullable<System.DateTime> BDATE { get; set; }
        public string IDCARDNO { get; set; }
        public Nullable<System.DateTime> IDCARDDAT { get; set; }
        public string BPLACE { get; set; }
        public string ALAMANA { get; set; }
        public Nullable<short> SEX { get; set; }
        public long TYP { get; set; }
        public long NAT { get; set; }
    
        public virtual ZNATION ZNATION { get; set; }
        public virtual ZPRSTYPE ZPRSTYPE { get; set; }
    }
}
