//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSclData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("DRIVINGSCHOOLS.ZREGION")]
    public partial class ZREGION
    {
        public ZREGION()
        {
            this.SCHOOL = new HashSet<SCHOOL>();
            this.ZCOMPANY = new HashSet<ZCOMPANY>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [ScaffoldColumn(false)]
        public long NB { get; set; }
        public string NAME { get; set; }
        [ScaffoldColumn(false)]
        public long CTY_NB { get; set; }
    
        public virtual ICollection<SCHOOL> SCHOOL { get; set; }
        public virtual ZCITY ZCITY { get; set; }
        public virtual ICollection<ZCOMPANY> ZCOMPANY { get; set; }
    }
}
