//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSclData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("DRIVINGSCHOOLS.ZSCLTYPE")]

    public partial class ZSCLTYPE
    {
        public ZSCLTYPE()
        {
            this.SCHOOL = new HashSet<SCHOOL>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public long NB { get; set; }
        public string TYPNAME { get; set; }
        public string NOTE { get; set; }
    
        public virtual ICollection<SCHOOL> SCHOOL { get; set; }
    }
}
