//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSclData
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("DRIVINGSCHOOLS.COMPANYOWNER")]

    public partial class COMPANYOWNER
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public long NB { get; set; }
        public long COMP_NB { get; set; }
        public long PRS_NB { get; set; }
        public string JOBTITLE { get; set; }
        public string NOTE { get; set; }
    
        public virtual ZCOMPANY ZCOMPANY { get; set; }
        public virtual ZPERSON ZPERSON { get; set; }
    }
}
