//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSclData
{
    using DrivingSclData;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("DRIVINGSCHOOLS.SCHOOLDOC")]

    public partial class SCHOOLDOC
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [ScaffoldColumn(false)]
        [DisplayName("الرمز الالكتروني")]
        public long NB { get; set; }
        public long SCL_NB { get; set; }
        public Nullable<System.DateTime> DAT { get; set; }
        public string NUM { get; set; }
        public long TYPE_NB { get; set; }
        public string ISSUER { get; set; }
        public string DESCRIB { get; set; }
        public long USAGE_NB { get; set; }
        public string DOCFILE { get; set; }
        public string NOTE { get; set; }
    
        public virtual SCHOOL SCHOOL { get; set; }
        public virtual ZDOCTYPE ZDOCTYPE { get; set; }
        public virtual ZDOCUSAGE ZDOCUSAGE { get; set; }
    }
}
