//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSclData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("DRIVINGSCHOOLS.SCHOOLOWNER")]
    public partial class SCHOOLOWNER
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public long NB { get; set; }
        public long SCL_NB { get; set; }
        public long OT_NB { get; set; }
        public long ONR_NB { get; set; }
        public string NOTE { get; set; }
    
        public virtual ZOWNERTYP ZOWNERTYP { get; set; }
        public virtual SCHOOL SCHOOL { get; set; }
    }
}
