//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSclData
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("DRIVINGSCHOOLS.SCHOOLTRAINER")]
    public partial class SCHOOLTRAINER
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public long NB { get; set; }
        public long PRS_NB { get; set; }
        public long SCL_NB { get; set; }
        public long TYP_NB { get; set; }
        public string DIPLOM { get; set; }
        public string LICENSENO { get; set; }
        public Nullable<System.DateTime> LICENSEDATE { get; set; }
        public string LICENSEFROM { get; set; }

        public virtual SCHOOL SCHOOL { get; set; }
        public virtual ZPERSON ZPERSON { get; set; }
        public virtual ZTRAINERTYPE ZTRAINERTYPE { get; set; }
    }
}
