//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSclData
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("DRIVINGSCHOOLS.SCHOOLVEHICLE")]
    public partial class SCHOOLVEHICLE
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public long NB { get; set; }
        public long SCL_NB { get; set; }
        public long GOV_NB { get; set; }
        public string BOARDNO { get; set; }
        public string VIN { get; set; }
        public string ENGINENO { get; set; }
        public Nullable<long> CLS_NB { get; set; }
        public string COLOR { get; set; }
        public string WIDTH { get; set; }
        public string LENG { get; set; }
        public Nullable<int> ENGINESIZE { get; set; }
        public Nullable<int> PRODYEAR { get; set; }
        public Nullable<int> REGYEAR { get; set; }
        public string BRAND { get; set; }
        public string MODELNO { get; set; }
        public Nullable<short> SEATS { get; set; }
        public Nullable<long> PRS_NB { get; set; }
        public Nullable<System.DateTime> LICENSEEXPIRYDATE { get; set; }
    
        public virtual SCHOOL SCHOOL { get; set; }
        public virtual ZVEHICLECLASS ZVEHICLECLASS { get; set; }
        public virtual ZGOVERN ZGOVERN { get; set; }
        public virtual ZPERSON ZPERSON { get; set; }
    }
}
