//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSclData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("DRIVINGSCHOOLS.ZCATEGORY")]
    public partial class ZCATEGORY
    {
        public ZCATEGORY()
        {
            this.ZCATEGORY1 = new HashSet<ZCATEGORY>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [ScaffoldColumn(false)]
        [DisplayName("الرمز الالكتروني")]
        public long NB { get; set; }
        [DisplayName("الفئة")]
        public string NAME { get; set; }
        [DisplayName("الفئة الواجب توافرها مسبقا")]
        public Nullable<long> PREV_CATG { get; set; }
        [DisplayName("عدد الطلاب لكل مركبة")]
        public int STUDENT_PER_CAR { get; set; }
        [DisplayName("عدد الطلاب لكل دراجة")]
        public Nullable<int> STUDENT_PER_MOTO { get; set; }
        [DisplayName("المساحة المطلوبة لكل طالب")]
        public decimal METERS_FOR_STUDENT { get; set; }
        [DisplayName("عدد الطلاب الأعظمي لكل قاعة")]
        public Nullable<int> MAX_STUDENTS_PER_HALL { get; set; }
        [DisplayName("ملاحظات")]
        public string NOTE { get; set; }
    
        public virtual ICollection<ZCATEGORY> ZCATEGORY1 { get; set; }
        public virtual ZCATEGORY ZCATEGORY2 { get; set; }
    }
}
