//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSclData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("DRIVINGSCHOOLS.ZCITY")]
    public partial class ZCITY
    {
        public ZCITY()
        {
            this.SCHOOL = new HashSet<SCHOOL>();
            this.ZCOMPANY = new HashSet<ZCOMPANY>();
            this.ZREGION = new HashSet<ZREGION>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [ScaffoldColumn(false)]
        [DisplayName("«·—„“ «·≈·ﬂ —Ê‰Ì")]
        public long NB { get; set; }
        [DisplayName("«·„œÌ‰…")]
        public string NAME { get; set; }
        [ScaffoldColumn(false)]
        public long GOV_NB { get; set; }
    
        public virtual ICollection<SCHOOL> SCHOOL { get; set; }
        public virtual ICollection<ZCOMPANY> ZCOMPANY { get; set; }
        public virtual ICollection<ZREGION> ZREGION { get; set; }
        public virtual ZGOVERN ZGOVERN { get; set; }
    }
}
