//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSclData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("DRIVINGSCHOOLS.ZDOCUSAGE")]

    public partial class ZDOCUSAGE
    {
        public ZDOCUSAGE()
        {
            this.SCHOOLDOCs = new HashSet<SCHOOLDOC>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [ScaffoldColumn(false)]
        public long NB { get; set; }
        public string USAGETYPE { get; set; }
    
        public virtual ICollection<SCHOOLDOC> SCHOOLDOCs { get; set; }
    }
}
