//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSclData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("DRIVINGSCHOOLS.ZDOCTYPE")]

    public partial class ZDOCTYPE
    {
        public ZDOCTYPE()
        {
            this.SCHOOLDOCs = new HashSet<SCHOOLDOC>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [ScaffoldColumn(false)]
        [DisplayName("الرمز الالكتروني")]
        public long NB { get; set; }
        [DisplayName("نوع الوثيقة")]
        public string DOCTYPE { get; set; }

        public virtual ICollection<SCHOOLDOC> SCHOOLDOCs { get; set; }
    }
}
